### ISSUE TITLE
Use of CMake

### ISSUE THREAD

**Issue by FederAndInk** [cristi1990an/Tensor-plus-plus#7]
If you change/add your sources (.cpp) you should change your CMakeLists.txt go see it, it's not a very complex one

you can read the doc for more details:
- https://cmake.org/cmake/help/latest/guide/tutorial/index.html
- https://www.youtube.com/watch?v=_yFPO1ofyF0&list=PLK6MXr8gasrGmIiSuVQXpfFuE1uPT615s

for more advance stuff, there is a lot of good talk:
- https://www.youtube.com/watch?v=bsXLMQ6WgIk

and here for an awesome list: https://github.com/onqtam/awesome-cmake

**Comment by cristi1990an** [comment]
I did! I've also drafted a pr that fixes all compilation issues with g++
and clang!

În mar., 13 iul. 2021 la 20:26, Ludovic J ***@***.***> a
scris:

**Comment by cristi1990an** [comment]
Would it be possible (or a good idea) to have clang-format be run
automatically on committed files?

În mar., 13 iul. 2021 la 20:38, Ludovic J ***@***.***> a
scris:

**Comment by FederAndInk** [comment]
Indeed, yes, you can look for git hooks
